## Numpy (short for Numerical Python)
Numpy is the core library for scientific computing in Python. 
It provides a high-performance multidimensional array object, and tools for working with these arrays.
Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science.


### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; 
The shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:


In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


### Array indexing
Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. 
Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [ ]:
# Array Creation
# There are several ways to create arrays.
# For example, you can create an array from a regular Python list or tuple using the array function. 
# The type of the resulting array is deduced from the type of the elements in the sequences.

import numpy as np

a = np.array([2,3,4])
print(a) # [2, 3, 4]
print(a.dtype) # dtype('int64')

b = np.array([1.2, 3.5, 5.1])
print(b.dtype) # dtype('float64')

# Array transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.
c = np.array([(1.5,2,3), (4,5,6)])
print(c)
# [[ 1.5,  2. ,  3. ],
#  [ 4. ,  5. ,  6. ]]

# The type of the array can also be explicitly specified at creation time:
d = np.array( [ [1,2], [3,4] ], dtype=complex )
print(d)
# [[ 1.+0.j,  2.+0.j],
#  [ 3.+0.j,  4.+0.j]]

e = np.arange(10, 30, 5) 
print(e) # [10, 15, 20, 25]

f = np.arange(0, 2, 0.3) # it accepts float arguments
print(f) # [ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8]


g = np.arange(15).reshape(3, 5)
print(g)
# [[ 0,  1,  2,  3,  4],
#  [ 5,  6,  7,  8,  9],
#  [10, 11, 12, 13, 14]]
print(g.shape) # (3, 5)
print(g.ndim) # 2
print(g.dtype.name) # 'int64'
print(g.size) # 15
print(type(g)) # <type 'numpy.ndarray'>

h = np.array([6, 7, 8])
print(h) # [6, 7, 8]
print(type(h)) # <type 'numpy.ndarray'>


[2 3 4]
int32
float64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [ ]:
# Using numpy.where(condition[, x, y])
# Return elements, either from x or y, depending on condition.
a = np.arange(9).reshape(3, 3)
print(a)

# Loop over all the elements. if the element < 5 => return the element, otherwise return -1
a = np.where(a < 5, a, -1) 
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4 -1]
 [-1 -1 -1]]


In [ ]:
# How to get index locations that satisfy a given condition using np.where?
a = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print(a)

# Positions where value > 5
index_gt5 = np.where(a > 5)
print("Positions where value > 5: ", index_gt5)

# Retrieve the corresponding values
print(a[index_gt5])

[8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4], dtype=int64),)
[8 8 7 7]
