## Numpy (short for Numerical Python)
Numpy is the core library for scientific computing in Python. 
It provides a high-performance multidimensional array object, and tools for working with these arrays.
Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science.

### Understanding Data Types in Python
Effective data-driven science and computation requires understanding how data is stored and manipulated. This section outlines and contrasts how arrays of data are handled in the Python language itself, and how NumPy improves on this. Users of Python are often drawn in by its ease of use, one piece of which is dynamic
typing. While a statically typed language like C or Java requires each variable to be explicitly declared, a dynamically typed language like Python skips this specification. For example, in C you might specify a particular operation as follows:
 
<code>
/* C code */
int result = 0;
for(int i=0; i<100; i++)
{
   result += i;
}
</code>
 
While in Python the equivalent operation could be written this way:
# Python code
result = 0
for i in range(100):
result += i

Notice the main difference: in C, the data types of each variable are explicitly
declared, while in Python the types are dynamically inferred. This means, for example,
that we can assign any kind of data to any variable:
# Python code
x = 4
x = "four"

Here we’ve switched the contents of x from an integer to a string. The same thing in C
would lead (depending on compiler settings) to a compilation error or other unintended
consequences:
/* C code */
int x = 4;
x = "four"; // FAILS

This sort of flexibility is one piece that makes Python and other dynamically typed
languages convenient and easy to use. Understanding how this works is an important
piece of learning to analyze data efficiently and effectively with Python. But what this
type flexibility also points to is the fact that Python variables are more than just their
value; they also contain extra information about the type of the value. 


## A Python Integer Is More Than Just an Integer
The standard Python implementation is written in C. This means that every Python
object is simply a cleverly disguised C structure, which contains not only its value, but
other information as well. For example, when we define an integer in Python, such as
x = 10000, x is not just a “raw” integer. It’s actually a pointer to a compound C structure,
which contains several values. Looking through the Python 3.4 source code, we
find that the integer (long) type definition effectively looks like this:
struct _longobject {
   long ob_refcnt;
   PyTypeObject *ob_type;
   size_t ob_size;
   long ob_digit[1];
};

A single integer in Python 3.4 actually contains four pieces:
• ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
• ob_type, which encodes the type of the variable
• ob_size, which specifies the size of the following data members
• ob_digit, which contains the actual integer value that we expect the Python variable to represent

This means that there is some overhead in storing an integer in Python as compared
to an integer in a compiled language like C

Notice the difference here: a C integer is essentially a label for a position in memory
whose bytes encode an integer value. A Python integer is a pointer to a position in
memory containing all the Python object information, including the bytes that contain
the integer value. This extra information in the Python integer structure is what
allows Python to be coded so freely and dynamically. All this additional information
in Python types comes at a cost, however, which becomes especially apparent in
structures that combine many of these objects.
"""

"""
A Python List Is More Than Just a List
Let’s consider now what happens when we use a Python data structure that holds
many Python objects. The standard mutable multielement container in Python is the
list. We can create a list of integers as follows:
L = list(range(10))
print(L)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

type(L[0]) # int

Or, similarly, a list of strings:

L2 = [str(c) for c in L]
print(L2) # ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
type(L2[0]) # str

Because of Python’s dynamic typing, we can even create heterogeneous lists:

L3 = [True, "2", 3.0, 4]
[type(item) for item in L3] # [bool, str, float, int]

But this flexibility comes at a cost: to allow these flexible types, each item in the list
must contain its own type info, reference count, and other information—that is, each
item is a complete Python object. In the special case that all variables are of the same
type, much of this information is redundant: it can be much more efficient to store
data in a fixed-type array. 
At the implementation level, the array essentially contains a single pointer to one contiguous
block of data. The Python list, on the other hand, contains a pointer to a
block of pointers, each of which in turn points to a full Python object like the Python
integer we saw earlier. Again, the advantage of the list is flexibility: because each list
element is a full structure containing both data and type information, the list can be
filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility,
but are much more efficient for storing and manipulating data.
"""

"""
Fixed-Type Arrays in Python
Python offers several different options for storing data in efficient, fixed-type data
buffers. The built-in array module (available since Python 3.3) can be used to create
dense arrays of a uniform type:
import array
L = list(range(10))
A = array.array('i', L)

print(A) # array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here 'i' is a type code indicating the contents are integers.
Much more useful, however, is the ndarray object of the NumPy package. While
Python’s array object provides efficient storage of array-based data, NumPy adds to
this efficient operations on that data.
"""

In [241]:
# Arrays
# A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
# The number of dimensions is the rank of the array; 
# The shape of an array is a tuple of integers giving the size of the array along each dimension.

# We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [242]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [243]:
# Numpy also provides many functions to create arrays:

import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.80124337 0.4965144 ]
 [0.70989059 0.25274244]]


In [244]:
# Array indexing
# Numpy offers several ways to index into arrays.

# Slicing: Similar to Python lists, numpy arrays can be sliced. 
# Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [245]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [246]:
# Array Creation
# There are several ways to create arrays.
# For example, you can create an array from a regular Python list or tuple using the array function. 
# The type of the resulting array is deduced from the type of the elements in the sequences.

import numpy as np

a = np.array([2,3,4])
print(a) # [2, 3, 4]
print(a.dtype) # dtype('int64')

b = np.array([1.2, 3.5, 5.1])
print(b.dtype) # dtype('float64')

# Array transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.
c = np.array([(1.5,2,3), (4,5,6)])
print(c)
# [[ 1.5,  2. ,  3. ],
#  [ 4. ,  5. ,  6. ]]

# The type of the array can also be explicitly specified at creation time:
d = np.array( [ [1,2], [3,4] ], dtype=complex )
print(d)
# [[ 1.+0.j,  2.+0.j],
#  [ 3.+0.j,  4.+0.j]]

e = np.arange(10, 30, 5) 
print(e) # [10, 15, 20, 25]

f = np.arange(0, 2, 0.3) # it accepts float arguments
print(f) # [ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8]


g = np.arange(15).reshape(3, 5)
print(g)
# [[ 0,  1,  2,  3,  4],
#  [ 5,  6,  7,  8,  9],
#  [10, 11, 12, 13, 14]]
print(g.shape) # (3, 5)
print(g.ndim) # 2
print(g.dtype.name) # 'int64'
print(g.size) # 15
print(type(g)) # <type 'numpy.ndarray'>

h = np.array([6, 7, 8])
print(h) # [6, 7, 8]
print(type(h)) # <type 'numpy.ndarray'>


[2 3 4]
int32
float64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [247]:
# Printing arrays
# When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
# - the last axis is printed from left to right,
# - the second-to-last is printed from top to bottom,
# - the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
# One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

import numpy as np
a = np.arange(6)                         # 1d array
print(a) # [0 1 2 3 4 5]

b = np.arange(12).reshape(4,3)           # 2d array
print(b)
# [[ 0  1  2]
# [ 3  4  5]
# [ 6  7  8]
# [ 9 10 11]]

c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)
# [[[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[12 13 14 15]
#  [16 17 18 19]
#  [20 21 22 23]]]

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [248]:
# Basic operations
# Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b) # [0, 1, 2, 3]
c = a-b
print(c) # [20, 29, 38, 47]
d = b**2 
print(d) # [0, 1, 4, 9]
e = 10*np.sin(a)
print(e) # [ 9.12945251, -9.88031624,  7.4511316 , -2.62374854]
f = a<35
print(f) # [ True, True, False, False]

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [249]:
# Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. 
# The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
print (A * B)                       # elementwise product
#[[2, 0],
# [0, 4]]
print (A @ B)                       # matrix product
#[[5, 4],
# [3, 4]]
print(A.dot(B))                 # another matrix product
#[[5, 4],
# [3, 4]]

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [250]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)
# [[3, 3, 3],
#   [3, 3, 3]]
b += a
print(b)
# [[ 3.417022  ,  3.72032449,  3.00011437],
#  [ 3.30233257,  3.14675589,  3.09233859]]

[[3 3 3]
 [3 3 3]]
[[3.80854545 3.40319173 3.92021787]
 [3.18642646 3.16630799 3.18194828]]


In [251]:
a = np.random.random((2,3))
print(a)
#[[ 0.18626021,  0.34556073,  0.39676747],
#  [ 0.53881673,  0.41919451,  0.6852195 ]]
print(a.sum()) # 2.5718191614547998
print(a.min()) # 0.1862602113776709
print(a.max()) # 0.6852195003967595

[[0.20057296 0.89948365 0.38395195]
 [0.49998465 0.24489591 0.61973575]]
2.8486248809780315
0.20057296047582773
0.899483654345258


In [252]:
# By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
# However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

b = np.arange(12).reshape(3,4)
print(b)
# [[ 0,  1,  2,  3],
#  [ 4,  5,  6,  7],
#  [ 8,  9, 10, 11]]
print(b.sum(axis=0))                            # sum of each column
# [12, 15, 18, 21]
print(b.min(axis=1))                            # min of each row
# [0, 4, 8]
print(b.cumsum(axis=1))                        # cumulative sum along each row
#[[ 0,  1,  3,  6],
# [ 4,  9, 15, 22],
# [ 8, 17, 27, 38]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [253]:
# Universal Functions
# NumPy provides familiar mathematical functions such as sin, cos, and exp. 
# In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

B = np.arange(3)
print(B) # [0, 1, 2]
print(np.exp(B)) # [ 1.        ,  2.71828183,  7.3890561 ]
print(np.sqrt(B)) # [ 0.        ,  1.        ,  1.41421356]
C = np.array([2., -1., 4.])
print(np.add(B, C)) #[ 2.,  0.,  6.]

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


In [254]:
# Indexing, Slicing and Iterating
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

a = np.arange(10)**3
print(a) # [  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]
print(a[2]) # 8
print(a[2:5]) # [ 8, 27, 64]
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a) # [-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729]
print(a[ : :-1])  # reversed a [  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000]

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [255]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)
# [[ 0,  1,  2,  3],
# [10, 11, 12, 13],
# [20, 21, 22, 23],
# [30, 31, 32, 33],
# [40, 41, 42, 43]]
print(b[2,3]) # 23
print(b[0:5, 1]) # each row in the second column of b [ 1, 11, 21, 31, 41]
print(b[ : ,1]) # equivalent to the previous example [ 1, 11, 21, 31, 41]
print(b[1:3, : ]) # each column in the second and third row of b
# [[10, 11, 12, 13],
#  [20, 21, 22, 23]]

# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

print(b[-1]) # the last row. Equivalent to b[-1,:] [40, 41, 42, 43]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


In [256]:
# The expression within brackets in b[i] is treated as an i followed by as many instances of : 
# as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].
# The dots (...) represent as many colons as needed to produce a complete indexing tuple. 
# For example, if x is an array with 5 axes, then

# x[1,2,...] is equivalent to x[1,2,:,:,:],
# x[...,3] to x[:,:,:,:,3] and
# x[4,...,5,:] to x[4,:,:,5,:]

c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
print(c.shape) # (2, 2, 3)
print(c[1,...]) # same as c[1,:,:] or c[1]
# [[100, 101, 102],
# [110, 112, 113]]
print(c[...,2]) # same as c[:,:,2]
# [[  2,  13],
#  [102, 113]])

(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [257]:
# Iterating over multidimensional arrays is done with respect to the first axis:

for row in b:
    print(row)

# [0 1 2 3]
# [10 11 12 13]
# [20 21 22 23]
# [30 31 32 33]
# [40 41 42 43]

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [258]:
# Shape Manipulation
# Changing the shape of an array
# An array has a shape given by the number of elements along each axis:

a = np.floor(10*np.random.random((3,4)))
print(a)
# [[ 2.,  8.,  0.,  6.],
#  [ 4.,  5.,  1.,  1.],
#  [ 8.,  9.,  3.,  6.]]
print(a.shape) # (3, 4)

[[8. 0. 1. 2.]
 [0. 9. 7. 1.]
 [0. 1. 2. 0.]]
(3, 4)


In [259]:
# The shape of an array can be changed with various commands. 
# Note that the following three commands all return a modified array, but do not change the original array:

print(a.ravel())  # returns the array, flattened
# [ 2.,  8.,  0.,  6.,  4.,  5.,  1.,  1.,  8.,  9.,  3.,  6.]
print(a.reshape(6,2))  # returns the array with a modified shape
# [[ 2.,  8.],
# [ 0.,  6.],
# [ 4.,  5.],
# [ 1.,  1.],
# [ 8.,  9.],
# [ 3.,  6.]]
print(a.T)  # returns the array, transposed
# [[ 2.,  4.,  8.],
# [ 8.,  5.,  9.],
# [ 0.,  1.,  3.],
# [ 6.,  1.,  6.]]
print(a.T.shape) # (4, 3)
print(a.shape) # (3, 4)

[8. 0. 1. 2. 0. 9. 7. 1. 0. 1. 2. 0.]
[[8. 0.]
 [1. 2.]
 [0. 9.]
 [7. 1.]
 [0. 1.]
 [2. 0.]]
[[8. 0. 0.]
 [0. 9. 1.]
 [1. 7. 2.]
 [2. 1. 0.]]
(4, 3)
(3, 4)


In [260]:
# The reshape function returns its argument with a modified shape, 
# whereas the ndarray.resize method modifies the array itself:

print(a)
# [[ 2.,  8.,  0.,  6.],
# [ 4.,  5.,  1.,  1.],
# [ 8.,  9.,  3.,  6.]]
a.resize((2,6))
print(a)
# [[ 2.,  8.,  0.,  6.,  4.,  5.],
#  [ 1.,  1.,  8.,  9.,  3.,  6.]]

[[8. 0. 1. 2.]
 [0. 9. 7. 1.]
 [0. 1. 2. 0.]]
[[8. 0. 1. 2. 0. 9.]
 [7. 1. 0. 1. 2. 0.]]


In [261]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

print(a.reshape(3,-1))
# [[ 2.,  8.,  0.,  6.],
#  [ 4.,  5.,  1.,  1.],
#  [ 8.,  9.,  3.,  6.]]

[[8. 0. 1. 2.]
 [0. 9. 7. 1.]
 [0. 1. 2. 0.]]


In [262]:
# Copies and Views
# When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. 
# This is often a source of confusion for beginners. There are three cases:

In [263]:
# No Copy at All
# Simple assignments make no copy of array objects or of their data.

a = np.arange(12)
b = a            # no new object is created
print(b is a)           # True --> a and b are two names for the same ndarray object
b.shape = 3,4    # changes the shape of a
print(a.shape) # (3, 4)

#Python passes mutable objects as references, so function calls make no copy.
def f(x):
    print(id(x))
    
print(id(a)) # id is a unique identifier of an object 148293216
print(f(a)) # 148293216

True
(3, 4)
2257458154112
2257458154112
None


In [264]:
# View or Shallow Copy
# Different array objects can share the same data. 
# The view method creates a new array object that looks at the same data.

c = a.view()
print(c is a) # False
print(c.base is a)  # True: c is a view of the data owned by a
print(c.flags.owndata) # False

c.shape = 2,6 # a's shape doesn't change
print(a.shape) # (3, 4)
c[0,4] = 1234 # a's data changes
print(a)
# [[   0,    1,    2,    3],
#  [1234,    5,    6,    7],
#  [   8,    9,   10,   11]]

# Slicing an array returns a view of it:

s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
print(a)
# [[   0,   10,   10,    3],
#  [1234,   10,   10,    7],
#  [   8,   10,   10,   11]]

False
True
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [265]:
# Deep Copy
# The copy method makes a complete copy of the array and its data.

d = a.copy() # a new array object with new data is created
print(d is a) # False
print(d.base is a) # False d doesn't share anything with a
d[0,0] = 9999
print(a)
# [[   0,   10,   10,    3],
#  [1234,   10,   10,    7],
#  [   8,   10,   10,   11]]

False
False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [266]:
# Fancy indexing and index tricks
# NumPy offers more indexing facilities than regular Python sequences. 
# In addition to indexing by integers and slices, as we saw before, 
# arrays can be indexed by arrays of integers and arrays of booleans.

In [267]:
# Indexing with Arrays of Indices
a = np.arange(12)**2  # the first 12 square numbers 
print(a) # [  0   1   4   9  16  25  36  49  64  81 100 121]
i = np.array( [ 1,1,3,8,5 ] ) # an array of indices
print(a[i]) # [ 1,  1,  9, 64, 25] the elements of a at the positions i
j = np.array( [ [ 3, 4], [ 9, 7 ] ] ) # a bidimensional array of indices
print(a[j]) # the same shape as j
# [[ 9, 16],
# [81, 49]]

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [268]:
# Booleans can be used for indexing; 
# for each dimension of the array we give a 1D boolean array selecting the slices we want:

a = np.arange(12).reshape(3,4)
print(a)
b1 = np.array([False,True,True])             # first dim selection
b2 = np.array([True,False,True,False])       # second dim selection

print(a[b1,:])  # selecting rows
# [[ 4,  5,  6,  7],
# [ 8,  9, 10, 11]]

print(a[b1]) # same thing
# [[ 4,  5,  6,  7],
#  [ 8,  9, 10, 11]]

print(a[:,b2])  # selecting columns
# [[ 0,  2],
# [ 4,  6],
# [ 8, 10]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [269]:
# Using numpy.where(condition[, x, y])
# Return elements, either from x or y, depending on condition.
a = np.arange(9).reshape(3, 3)
print(a)

# Loop over all the elements. if the element < 5 => return the element, otherwise return -1
a = np.where(a < 5, a, -1) 
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4 -1]
 [-1 -1 -1]]


In [270]:
# How to get index locations that satisfy a given condition using np.where?
a = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print(a)

# Positions where value > 5
index_gt5 = np.where(a > 5)
print("Positions where value > 5: ", index_gt5)

# Retrieve the corresponding values
print(a[index_gt5])

[8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4], dtype=int64),)
[8 8 7 7]
