In [9]:
import numpy as np

In [1]:
# Manually create the following array a: [0, 1, 2, 3]

# Print the array


# Print the number of array dimensions of the array


#  Print the current shape of the array



In [2]:
# Manually create the following array b: ([0, 1, 2], [3, 4, 5])


# Print the array


# What is the number of array dimensions of the array


# What is the current shape of the array



In [3]:
# In practice, we rarely enter items one by one
# Create the following array a: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Print the array


# Create the following array b: ([1, 3, 5, 7])


# Print the array


In [4]:
# Common arrays
# Create the following array a 
# [[ 1.  1.  1.]
# [ 1.  1.  1.]
# [ 1.  1.  1.]]


# Print the array


# Create the following array b
# [[ 0.  0.]
# [ 0.  0.]]


# Print the array


# Create the following array c
# [[ 1.  0.  0.]
# [ 0.  1.  0.]
# [ 0.  0.  1.]]


# Print the array


# Create the following array d (random numbers)
# [ 0.60733288  0.03138041  0.41180997  0.44638799]


# Print the array



In [5]:
# In some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2)
# This is due to a difference in the data-type used
# Create the array a: ([1, 2, 3])


# Print the datatype


# Create the array b: ([1., 2., 3.])


# Print the datatype



In [6]:
# Create the array a: ([1, 2, 3]). Specify the data-type as float


# Print the array


# Print the datatype



In [7]:
# Create the array 3 x 3 unity matrix a. What is the default data-type


# Print the array


# Print the datatype



In [8]:
# Create the array a: ([True, False, False, True]).


# Print the array


# Print the datatype



In [9]:
# Create the array a: (['Bonjour', 'Hello', 'Hallo']).


# Print the array


# Print the datatype



In [10]:
# Indexing and slicing
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])


# Print the array


# Print the element with index 0, 2, -1


# Print the reverse of array a



In [12]:
# For multidimensional arrays, indexes are tuples of integers:
# Create the array a


# Print the array


# Print the value of the second line, second column


# Change the value of the third line, second column to 10


# Print the array


# Print the second row of the array



In [11]:
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])


# Print the array


# Print the first 4 elements. Use slicing


# Print [2, 5, 8]. Use slicing [start:end:step]


# All three slice components are not required: by default, start is 0, end is the last and step is 1
# Print ([1, 2]). Use slicing


# Print ([0, 2, 4, 6, 8]). Use slicing


# Print ([3, 4, 5, 6, 7, 8, 9]). Use slicing



In [14]:
# You can also combine assignment and slicing
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])


# Print the array


# Change the array a to ([0 1 2 3 4 10 10 10 10 10]). Use slicing


# Print the array



In [15]:
# Create the array a
# [[ 0  1  2  3  4  5]
# [10 11 12 13 14 15]
# [20 21 22 23 24 25]
# [30 31 32 33 34 35]
# [40 41 42 43 44 45]
# [50 51 52 53 54 55]]


# Print the array



In [16]:
# Create the following array (with correct data type)
# [[1 1 1 1]
# [1 1 1 1]
# [1 1 1 2]
# [1 6 1 1]]


# Print the array


In [17]:
# Create the following array
# [[2 0 0 0 0]
# [0 3 0 0 0]
# [0 0 4 0 0]
# [0 0 0 5 0]
# [0 0 0 0 6]]


# Print the array


In [18]:
# Copies and views
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])


# Print the array a


# Copy the even numbers into an array b


# Print the array b


# replace value 0 in array b by 12


# Print the arrays b en a


# Create the array a: ([0 1 2 3 4 5 6 7 8 9])


# Print the array a


# force a copy of the even numbers into an array c. Use .copy()


# replace value 0 in array c by 12


# Print the array c en a


In [19]:
# Create the array a: ([0 10 20 30 40 50 60 70 80 90])


# Print the array a


# Use an array of integers for indexing, to get the array [20, 30, 20, 40, 20]


# Use an array of integers for indexing, to replace 70 and 90 by -100


# Print the array a


In [21]:
# Create the array a: ([1 2 3 4])


# Print the array a


# Print the array [2 3 4 5] based on the array a


# Print the array [ 2  4  8 16] based on the array a


# Create the array b [1 1 1 1]

# Print the array b


# Add 1 to each element of the array b


# Print the array b


# Subtract b from a. Print the result


# Multiply a and b. Print the result


# Create the array c 
# [[1 1 1],
# [1 1 1],
# [1 1 1]]


# Print the array c


# Print the result of c * c


# Print the result of c @ c



In [20]:
# Create the array a: ([1 2 3 4 5 6 7 8 9])


# Print the array a


# Print the sum of all elements of a


# Print the min and max of all elements of a



# Transform the array to a 3 x 3 matrix


# Print the array a


# Print the sum along axis = 0


# Print the sum along axis = 1


# Print the max along axis = 1


# Transpose the matrix a


# Flatten the matrix a



In [ ]:
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])


# Print the array a


# Change the array a: ([0 1 2 3 4 50 60 70 80 90]) to using where


# Print the array a

