In [2]:
import numpy as np

In [10]:
# Manually create the following array a: [0, 1, 2, 3]
a = np.array([0, 1, 2, 3])
# Print the array
print(a)

# What is the number of array dimensions of the array
print(a.ndim)

# What is the current shape of the array
print(a.shape)


[0 1 2 3]
1
(4,)


In [11]:
# Manually create the following array b: ([0, 1, 2], [3, 4, 5])
b = np.array([[0, 1, 2], [3, 4, 5]])
# Print the array
print(b)

# What is the number of array dimensions of the array
print(b.ndim)

# What is the current shape of the array
print(b.shape)


[[0 1 2]
 [3 4 5]]
2
(2, 3)


In [14]:
# In practice, we rarely enter items one by one
# Create the following array a: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.arange(10)
# Print the array
print(a)
# Create the following array b: ([1, 3, 5, 7])
b = np.arange(1, 9, 2)
# Print the array
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [17]:
# Common arrays
# Create the following array a 
# [[ 1.  1.  1.]
# [ 1.  1.  1.]
# [ 1.  1.  1.]]
a = np.ones((3,3))
# Print the array
print(a)
# Create the following array b
# [[ 0.  0.]
# [ 0.  0.]]
b = np.zeros((2, 2))
# Print the array
print(b)
# Create the following array c
# [[ 1.  0.  0.]
# [ 0.  1.  0.]
# [ 0.  0.  1.]]
c = np.eye(3)
# Print the array
print(c)
# Create the following array d (random numbers)
# [ 0.60733288  0.03138041  0.41180997  0.44638799]
d = np.random.rand(4)
# Print the array
print(d)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[ 0.60733288  0.03138041  0.41180997  0.44638799]


In [19]:
# In some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2)
# This is due to a difference in the data-type used
# Create the array a: ([1, 2, 3])
a = np.array([1, 2, 3])
# Print the datatype
print(a.dtype)
# Create the array b: ([1., 2., 3.])
b = np.array([1., 2., 3.])
# Print the datatype
print(b.dtype)

int32
float64


In [21]:
# Create the array a: ([1, 2, 3]). Specify the data-type as float
a = np.array([1, 2, 3], dtype=float)
# Print the array
print(a)
# Print the datatype
print(a.dtype)

[ 1.  2.  3.]
float64


In [23]:
# Create the array 3 x 3 unity matrix a. What is the default data-type
a = np.eye(3)
# Print the array
print(a)
# Print the datatype
print(a.dtype)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
float64


In [24]:
# Create the array a: ([True, False, False, True]).
a = np.array([True, False, False, True])
# Print the array
print(a)
# Print the datatype
print(a.dtype)

[ True False False  True]
bool


In [25]:
# Create the array a: (['Bonjour', 'Hello', 'Hallo']).
a = np.array(['Bonjour', 'Hello', 'Hallo'])
# Print the array
print(a)
# Print the datatype
print(a.dtype)

['Bonjour' 'Hello' 'Hallo']
<U7


In [33]:
# Indexing and slicing
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])
a = np.arange(10)
# Print the array
print(a)
# Print the element with index 0, 2, -1
print(a[0], a[2], a[-1])
# Print the reverse of array a
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
0 2 9
[9 8 7 6 5 4 3 2 1 0]


In [34]:
# For multidimensional arrays, indexes are tuples of integers:
# Create the array a
a = np.diag(np.arange(3))
# Print the array
print(a)
# Print the value of the second line, second column
print(a[1, 1])
# Change the value of the third line, second column to 10
a[2, 1] = 10
# Print the array
print(a)
# Print the second row of the array
print(a[1])

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[[ 0  0  0]
 [ 0  1  0]
 [ 0 10  2]]
[0 1 0]


In [37]:
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])
a = np.arange(10)
# Print the array
print(a)
# Print the first 4 elements. Use slicing
print(a[:4])
# Print [2, 5, 8]. Use slicing [start:end:step]
print(a[2:9:3])
# All three slice components are not required: by default, start is 0, end is the last and step is 1
# Print ([1, 2]). Use slicing
print(a[1:3])
# Print ([0, 2, 4, 6, 8]). Use slicing
print(a[::2])
# Print ([3, 4, 5, 6, 7, 8, 9]). Use slicing
print(a[3:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[2 5 8]
[1 2]
[0 2 4 6 8]
[3 4 5 6 7 8 9]


In [38]:
# You can also combine assignment and slicing
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])
a = np.arange(10)
# Print the array
print(a)
# Change the array a to ([0 1 2 3 4 10 10 10 10 10]). Use slicing
a[5:] = 10
# Print the array
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 10 10 10 10 10]


In [43]:
# Create the array a
a = np.arange(6) + np.arange(0, 51, 10)[:,np.newaxis]
# Print the array
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [47]:
# Create the following array (with correct data type)
# [[1 1 1 1]
# [1 1 1 1]
# [1 1 1 2]
# [1 6 1 1]]
a = np.ones((4, 4), dtype=int)
a[2, 3] = 2
a[3, 1] = 6
# Print the array
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 6 1 1]]


In [68]:
# Create the following array
# [[2 0 0 0 0]
# [0 3 0 0 0]
# [0 0 4 0 0]
# [0 0 0 5 0]
# [0 0 0 0 6]]
a = np.diag(np.arange(7))
b = a[2:, 2:]
# Print the array


print(b)

[[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]


In [76]:
# Copies and views
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])
a = np.arange(10)
# Print the array a
print(a)
# Copy the even numbers into an array b
b = a[::2]
# Print the array b
print(b)
# replace value 0 in array b by 12
b[0] = 12
# Print the array b en a
print(b)
print(a)

# Create the array a: ([0 1 2 3 4 5 6 7 8 9])
a = np.arange(10)
# Print the array a
print(a)
# force a copy of the even numbers into an array c
c = a[::2].copy()
# replace value 0 in array c by 12
c[0] = 12
# Print the array c en a
print(c)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[12  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


In [81]:
# Create the array a: ([0 10 20 30 40 50 60 70 80 90])
a = np.arange(0, 100, 10)
# Print the array a
print(a)

# Use an array of integers for indexing, to get the array [20, 30, 20, 40, 20]
print(a[[2, 3, 2, 4, 2]])

# Use an array of integers for indexing, to replace 70 and 90 by -100
a[[9, 7]] = -100

# Print the array a
print(a)

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20]
[   0   10   20   30   40   50   60 -100   80 -100]


In [96]:
# Create the array a: ([1 2 3 4])
a = np.arange(1, 5)
# Print the array a
print(a)

# Print the array [2 3 4 5] based on the array a
print (a + 1)

# Print the array [ 2  4  8 16] based on the array a
print (2 ** a)

# Create the array b [1 1 1 1]
b = np.ones(4)
# Print the array b
print(b)

# Add 1 to each element of the array b
b = b + 1
# Print the array b
print(b)

# Subtract b from a. Print the result
print(a - b)
# Multiply a and b. Print the result
print(a*b)

# Create the array c 
# [[1 1 1],
# [1 1 1],
# [1 1 1]]
c = np.ones((3, 3))
# Print the array c
print(c)

# Print the result of c * c
print(c * c)
# Print the result of c @ c
print(c @ c)

[1 2 3 4]
[2 3 4 5]
[ 2  4  8 16]
[ 1.  1.  1.  1.]
[ 2.  2.  2.  2.]
[-1.  0.  1.  2.]
[ 2.  4.  6.  8.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]]


In [108]:
# Create the array a: ([1 2 3 4 5 6 7 8 9])
a = np.arange(1, 10)
# Print the array a
print(a)
# Print the sum of all elements of a
print(np.sum(a))
# Print the min and max of all elements of a
print(np.min(a))
print(np.max(a))
# Transform the array to a 3 x 3 matrix
a.resize((3,3))
# Print the array a
print(a)
# Print the sum along axis = 0
print(a.sum(axis=0))
# Print the sum along axis = 1
print(a.sum(axis=1))
# Print the max along axis = 1
print(a.max(axis=1))
# Transpose the matrix a
print(a.T)
# Flatten the matrix a
print(a.ravel())

[1 2 3 4 5 6 7 8 9]
45
1
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[3 6 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]


In [4]:
# Create the array a: ([0 1 2 3 4 5 6 7 8 9])
a = np.arange(0, 10)
# Print the array a
print(a)
# Change the array a: ([0 1 2 3 4 50 60 70 80 90]) to using where
a = np.where(a < 5, a, 10*a)
# Print the array a
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]
